[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
esusux = "CG2XsN5oeS1QzEUn3cuaqJb67uaAXgxMpPYsD9Qv5wJp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
